version: '3.8'

services:
    app:
        build: .
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        volumes:
            - ./:/app
        ports:
            - "1337:1337"
        command: sleep infinity

